AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  PR Narrator Lambda with S3 for storing audio output

Globals:
  Function:
    Timeout: 15

Resources:
  NarratorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "genai-narrator-${AWS::AccountId}-${AWS::Region}"

  NarratorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pr-narrator
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: narrator-lambda/
      MemorySize: 512
      Environment:
        Variables:
          S3_BUCKET: !Ref NarratorBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref NarratorBucket
        - Statement:
            Effect: Allow
            Action:
              - "bedrock:InvokeModel"
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "*"
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: ["*"]

Outputs:
  NarratorLambdaArn:
    Description: The ARN of the Narrator Lambda
    Value: !GetAtt NarratorLambda.Arn
  BucketName:
    Description: Where MP3 files are stored
    Value: !Ref NarratorBucket
