version = 0.1
[default.deploy.parameters]
stack_name = "genai-app"
resolve_s3 = true
s3_prefix = "genai-app"
region = "us-east-1"
profile = "rahul"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
